#!/bin/sh
### General options
### ?- specify queue --
#BSUB -q gpuv100
### -- set the job Name --
#BSUB -J fairseq
### -- ask for number of cores (default: 1) --
#BSUB -n 2
### -- Select the resources: 1 gpu in exclusive process mode --
#BSUB -gpu "num=4"
### -- set walltime limit: hh:mm --  maximum 24 hours for GPU-queues right now
#BSUB -W 20:00
# request 5GB of system-memory
#BSUB -R "rusage[mem=20GB]"
#BSUB -R "select[gpu32gb]"
### -- set the email address --
# please uncomment the following line and put in your e-mail address,
# if you want to receive e-mail notifications on a non-default address
##BSUB -u your_email_address
### -- send notification at start --
##BSUB -B
### -- send notification at completion--
#BSUB -N
### -- Specify the output and error file. %J is the job-id --
### -- -o and -e mean append, -oo and -eo mean overwrite --
#BSUB -o fairseq_%J.out
#BSUB -e fairseq_%J.err
# -- end of LSF options --

# module load cuda/10.1
# module load python3

# pip3 install -r requirements.txt --user

python3 -m wandb.cli login 789d100f03fa3d5dbfbe897a22e4b9f08ed01598
python3 -m wandb.cli on

python3 train.py \
    data-bin/gec_filtered \
    --job-name error_generator \
    --arch transformer_vaswani_wmt_en_de_big --share-all-embeddings \
    --save-dir checkpoints/err_generator_filtered \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --lr 0.0005 --lr-scheduler inverse_sqrt --warmup-updates 4000 --warmup-init-lr 1e-07 \
    --dropout 0.3 --weight-decay 0.0 \
    --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
    --max-update 20000 \
    --max-tokens 8000 \
    --fp16 \
    --keep-last-epochs 3