#!/bin/sh
### General options
### ?- specify queue --
#BSUB -q gpuv100
### -- set the job Name --
#BSUB -J fairseq
### -- ask for number of cores (default: 1) --
#BSUB -n 2
### -- Select the resources: 1 gpu in exclusive process mode --
#BSUB -gpu "num=4"
### -- set walltime limit: hh:mm --  maximum 24 hours for GPU-queues right now
#BSUB -W 1:00
# request 5GB of system-memory
#BSUB -R "rusage[mem=20GB]"
#BSUB -R "select[gpu32gb]"
### -- set the email address --
# please uncomment the following line and put in your e-mail address,
# if you want to receive e-mail notifications on a non-default address
##BSUB -u your_email_address
### -- send notification at start --
##BSUB -B
### -- send notification at completion--
#BSUB -N
### -- Specify the output and error file. %J is the job-id --
### -- -o and -e mean append, -oo and -eo mean overwrite --
#BSUB -o fairseq_%J.out
#BSUB -e fairseq_%J.err
# -- end of LSF options --

ulimit -s unlimited
# module load cuda/10.1
# module load python3

# pip3 install -r requirements.txt --user

# python3 -m wandb.cli login 789d100f03fa3d5dbfbe897a22e4b9f08ed01598
# python3 -m wandb.cli on

# python3 fairseq_cli/train.py \
#     data-bin/wmt14_en_de \
#     --save-dir checkpoints/levt \
#     --ddp-backend=no_c10d \
#     --task translation_lev \
#     --criterion nat_loss \
#     --arch levenshtein_transformer \
#     --noise random_delete \
#     --share-all-embeddings \
#     --optimizer adam --adam-betas '(0.9,0.98)' \
#     --lr 0.0005 --lr-scheduler inverse_sqrt \
#     --min-lr '1e-09' --warmup-updates 10000 \
#     --warmup-init-lr '1e-07' --label-smoothing 0.1 \
#     --dropout 0.3 --weight-decay 0.01 \
#     --decoder-learned-pos \
#     --encoder-learned-pos \
#     --apply-bert-init \
#     --log-format 'simple' --log-interval 100 \
#     --fixed-validation-seed 7 \
#     --max-tokens 8000 \
#     --save-interval-updates 10000 \
#     --max-update 300000

python3 train.py \
    data-bin/joint-bpe-37k \
    --arch transformer --share-decoder-input-output-embed \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 \
    --dropout 0.3 --weight-decay 0.0001 \
    --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
    --max-tokens 8182 --fp16 --keep-last-epochs 2